#!/usr/bin/env bash

docker run -d --name bitlbee -v /etc/state/bitlbee:/bitlbee/state mfaerevaag/bitlbee:latest
docker run -d --name znc --link bitlbee:bitlbee -p 6668:6668 -v /etc/state/znc:/znc/state mfaerevaag/znc:latest
